const business={name:'SMM Boost Studio',whatsappNumber:'10000000000',currency:'USD'};
const packages=[{id:'starter',name:'Starter',price:49,description:'Para ordenar la presencia digital de una marca pequeña.',featured:false,features:['Auditoría básica de perfil','10 ideas de contenido','Optimización de biografía','Calendario de 7 días','1 reporte básico']},{id:'growth',name:'Growth',price:149,description:'Para negocios que quieren publicar mejor y captar clientes.',featured:true,features:['Auditoría completa','30 ideas de contenido','10 guiones cortos','Calendario de 30 días','Optimización de campaña','Reporte semanal']},{id:'pro',name:'Pro',price:299,description:'Para marcas que quieren estrategia, contenido y seguimiento.',featured:false,features:['Estrategia mensual SMM','20 guiones UGC','Plan para anuncios','Optimización de funnel','Reporte avanzado','Soporte prioritario']}];
const pricingGrid=document.getElementById('pricingGrid');const packageSelect=document.getElementById('packageSelect');const orderForm=document.getElementById('orderForm');const summaryBox=document.getElementById('summaryBox');const whatsappBtn=document.getElementById('whatsappBtn');const copyBtn=document.getElementById('copyBtn');const toast=document.getElementById('toast');const menuBtn=document.getElementById('menuBtn');const navLinks=document.getElementById('navLinks');const themeBtn=document.getElementById('themeBtn');let currentSummary='';
function money(value){return new Intl.NumberFormat('en-US',{style:'currency',currency:business.currency}).format(value)}
function safe(str){return String(str).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function renderPackages(){pricingGrid.innerHTML=packages.map(pkg=>`<article class="priceCard ${pkg.featured?'featured':''}">${pkg.featured?'<span class="badge">Más recomendado</span>':''}<h3>${pkg.name}</h3><p>${pkg.description}</p><div class="price">${money(pkg.price)} <span>/ proyecto</span></div><ul class="features">${pkg.features.map(item=>`<li>${item}</li>`).join('')}</ul><a href="#pedido" class="btn ${pkg.featured?'primary':'secondary'}" data-package="${pkg.id}">Elegir ${pkg.name}</a></article>`).join('');packageSelect.innerHTML='<option value="">Seleccionar paquete</option>'+packages.map(pkg=>`<option value="${pkg.id}">${pkg.name} - ${money(pkg.price)}</option>`).join('');document.querySelectorAll('[data-package]').forEach(btn=>{btn.addEventListener('click',()=>{packageSelect.value=btn.dataset.package;setTimeout(()=>document.getElementById('clientName').focus(),250)})})}
function buildSummary(data){const pkg=packages.find(item=>item.id===data.packageId);const adBudget=Number(data.adBudget||0);const total=pkg.price+adBudget;return{pkg,adBudget,total,text:`Nuevo pedido de marketing SMM\n\nMarca / Cliente: ${data.clientName}\nContacto: ${data.clientContact}\nRed principal: ${data.platform}\nPaquete: ${pkg.name} - ${money(pkg.price)}\nPresupuesto extra para anuncios: ${money(adBudget)}\nEstimado inicial: ${money(total)}\n\nObjetivo:\n${data.goal}\n\nEnviado desde ${business.name}`}}
function updateSummaryHTML(summary){summaryBox.innerHTML=`<p><strong>Cliente:</strong> ${safe(document.getElementById('clientName').value)}</p><p><strong>Red:</strong> ${safe(document.getElementById('platform').value)}</p><p><strong>Paquete:</strong> ${summary.pkg.name} — ${money(summary.pkg.price)}</p><p><strong>Ads extra:</strong> ${money(summary.adBudget)}</p><p><strong>Total estimado:</strong> ${money(summary.total)}</p><hr style="border:0;border-top:1px solid var(--line);margin:12px 0"><p><strong>Objetivo:</strong><br>${safe(document.getElementById('goal').value)}</p>`}
function enableActions(text){whatsappBtn.href=`https://wa.me/${business.whatsappNumber}?text=${encodeURIComponent(text)}`;whatsappBtn.classList.remove('disabled');copyBtn.disabled=false}
orderForm.addEventListener('submit',event=>{event.preventDefault();const data={clientName:document.getElementById('clientName').value.trim(),clientContact:document.getElementById('clientContact').value.trim(),platform:document.getElementById('platform').value,packageId:document.getElementById('packageSelect').value,goal:document.getElementById('goal').value.trim(),adBudget:document.getElementById('adBudget').value};if(!data.clientName||!data.clientContact||!data.platform||!data.packageId||!data.goal){alert('Completa todos los campos obligatorios.');return}const summary=buildSummary(data);currentSummary=summary.text;updateSummaryHTML(summary);enableActions(currentSummary)});
copyBtn.addEventListener('click',async()=>{if(!currentSummary)return;try{await navigator.clipboard.writeText(currentSummary);toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}catch(e){alert('No se pudo copiar automáticamente. Copia el resumen manualmente.')}});
menuBtn.addEventListener('click',()=>navLinks.classList.toggle('open'));document.querySelectorAll('.links a').forEach(link=>link.addEventListener('click',()=>navLinks.classList.remove('open')));
themeBtn.addEventListener('click',()=>{document.documentElement.classList.toggle('light');const light=document.documentElement.classList.contains('light');themeBtn.textContent=light?'☀️':'🌙';localStorage.setItem('theme',light?'light':'dark')});if(localStorage.getItem('theme')==='light'){document.documentElement.classList.add('light');themeBtn.textContent='☀️'}
document.getElementById('year').textContent=new Date().getFullYear();renderPackages();
